name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.15, windows-2019]
        java: [8, 11, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Test
        run: mvn clean test --errors --batch-mode

  lint:
    name: Linters
    runs-on: ubuntu-18.04
    steps:
      - name: JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Qulice
        run: mvn -P qulice clean install -DskipTests=true --errors --batch-mode
      - name: Site
        run: mvn -P site clean site --errors --batch-mode
